
#
# PROGRAM: sorting
# AUTHOR:  Mosab Rezaei
#

CXXFLAGS+=-Wall -Werror -std=c++11

PROGS=merge_sort quick_sort bubble_sort selection_sort insertion_sort

.PHONY: all clean world

all: $(PROGS)

clean:
        rm -f *.o $(PROGS)

world: clean all
